platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'Masonry'
pod 'SDWebImage','~>3.7.2'
pod 'JSONModel', '~> 1.1.0'
pod 'MBProgressHUD', '~> 0.9.1'

pod 'Reveal-iOS-SDK', :configurations => ['Debug']
